spring:
  application:
     name: lbgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          
      routes:

        - id: lbservice-route

          uri: lb://BUDGET

          predicates:
            - Path=/budgets/**



        - id: lbservice2-route

          uri: lb://EXPENSE

          predicates:
            - Path=/expenses/**


server:
  port: 8888
  
  
management:
  endpoint:
  
    gateway:
      enabled: true
  
  
  
